# Generated by Django 3.1.2 on 2021-03-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password2',
        ),
    ]
