# Generated by Django 3.1.2 on 2021-03-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210316_0052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
