# Generated by Django 3.1.2 on 2021-03-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_answers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answers',
            table='answers',
        ),
    ]
