# Generated by Django 3.1.2 on 2021-03-18 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210319_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='r1',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
