# Generated by Django 3.1.2 on 2021-03-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alllogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllLogin',
        ),
    ]
