# Generated by Django 3.1.2 on 2021-03-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_alllogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='level3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_data', models.CharField(max_length=60)),
                ('img_src', models.ImageField(upload_to='static/l3images')),
            ],
        ),
    ]
