# Generated by Django 3.1.2 on 2021-03-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_level3'),
    ]

    operations = [
        migrations.AddField(
            model_name='level3',
            name='img_flag',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='level3',
            name='img_data',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='level3',
            name='img_src',
            field=models.ImageField(default='', upload_to='static/l3images'),
        ),
    ]
