# Generated by Django 3.1.2 on 2021-03-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_level3_img_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='level3',
            new_name='level3data',
        ),
    ]
