# Generated by Django 3.1.2 on 2021-03-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210329_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='level1data',
            name='img_id',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='level2data',
            name='img_id',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='level3data',
            name='img_id',
            field=models.CharField(default='', max_length=60),
        ),
    ]
