# Generated by Django 3.1.2 on 2021-04-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210330_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='clickCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(default='', max_length=60)),
                ('count', models.IntegerField(default=0)),
                ('AdditionalCount', models.IntegerField(default=0)),
            ],
        ),
    ]
