# Generated by Django 3.1.2 on 2021-04-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(default='', max_length=60)),
                ('score', models.IntegerField(default=0)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
