# Generated by Django 3.1.2 on 2021-04-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_finalscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalscore',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
