# Generated by Django 3.1.2 on 2021-04-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_finalscore_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level2data',
            name='img_id',
        ),
    ]
