# Generated by Django 3.1.2 on 2021-04-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_level2data_img_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level2data',
            name='id',
        ),
        migrations.AlterField(
            model_name='level2data',
            name='img_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
