# Generated by Django 3.1.2 on 2021-04-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20210419_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ccount',
        ),
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
