# Generated by Django 3.1.2 on 2021-04-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20210419_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('score', models.IntegerField(default=0)),
                ('level1', models.CharField(default='', max_length=60)),
                ('level1ClickCount', models.IntegerField(default=0)),
                ('level1Hint', models.CharField(default='', max_length=60)),
                ('level1AddClick', models.IntegerField(default=0)),
                ('level2', models.CharField(default='', max_length=60)),
                ('level2ClickCount', models.IntegerField(default=0)),
                ('level2Hint', models.CharField(default='', max_length=60)),
                ('level2AddClick', models.IntegerField(default=0)),
                ('level3', models.CharField(default='', max_length=60)),
                ('level3ClickCount', models.IntegerField(default=0)),
                ('level3Hint', models.CharField(default='', max_length=60)),
                ('level3AddClick', models.IntegerField(default=0)),
            ],
        ),
    ]
