# Generated by Django 3.1.2 on 2021-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='level1ClickCount',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='level2ClickCount',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='level3ClickCount',
            field=models.IntegerField(default=3),
        ),
    ]
