# Generated by Django 3.1.2 on 2021-04-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20210419_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level1data',
            name='img_flag',
        ),
        migrations.RemoveField(
            model_name='level2data',
            name='img_flag',
        ),
        migrations.RemoveField(
            model_name='level3data',
            name='img_flag',
        ),
    ]
