# Generated by Django 3.1.2 on 2021-04-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20210419_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clickCount',
        ),
    ]
