# Generated by Django 3.1.2 on 2021-04-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_delete_clickcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='clickedImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('imgId', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='currentLevel',
            field=models.IntegerField(default=0),
        ),
    ]
