# Generated by Django 3.1.2 on 2021-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20210420_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Clevel',
            field=models.CharField(default='index', max_length=60),
        ),
    ]
