# Generated by Django 3.1.2 on 2021-04-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_userinfo_clevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Clevel',
            field=models.CharField(default='level1', max_length=60),
        ),
    ]
