# Generated by Django 3.1.2 on 2021-04-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20210420_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='level2data',
        ),
    ]
