# Generated by Django 3.1.2 on 2021-04-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_delete_level2data'),
    ]

    operations = [
        migrations.CreateModel(
            name='level2data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(default='', max_length=60)),
                ('img_id', models.CharField(default='', max_length=60)),
                ('img_data', models.CharField(default='', max_length=60)),
                ('img_src', models.ImageField(default='', upload_to='static/l3images')),
            ],
        ),
    ]
