# Generated by Django 3.1.2 on 2021-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_level2data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='level1score',
            field=models.CharField(default='false', max_length=60),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level2score',
            field=models.CharField(default='false', max_length=60),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level3score',
            field=models.CharField(default='false', max_length=60),
        ),
    ]
