# Generated by Django 3.1.2 on 2021-04-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_auto_20210429_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='level4data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(default='', max_length=60)),
                ('img_id', models.CharField(default='', max_length=60)),
                ('img_data', models.TextField()),
                ('img_src', models.ImageField(default='', upload_to='static/l3images')),
            ],
        ),
        migrations.CreateModel(
            name='level5data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(default='', max_length=60)),
                ('img_id', models.CharField(default='', max_length=60)),
                ('img_data', models.TextField()),
                ('img_src', models.ImageField(default='', upload_to='static/l3images')),
            ],
        ),
        migrations.CreateModel(
            name='level6data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(default='', max_length=60)),
                ('img_id', models.CharField(default='', max_length=60)),
                ('img_data', models.TextField()),
                ('img_src', models.ImageField(default='', upload_to='static/l3images')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='level1Hint',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='level2Hint',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='level3Hint',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level4',
            field=models.CharField(default='level4', max_length=60),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level4AddClick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level4ClickCount',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level4score',
            field=models.CharField(default='false', max_length=60),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level5',
            field=models.CharField(default='level5', max_length=60),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level5AddClick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level5ClickCount',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level5score',
            field=models.CharField(default='false', max_length=60),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level6',
            field=models.CharField(default='level6', max_length=60),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level6AddClick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level6ClickCount',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level6score',
            field=models.CharField(default='false', max_length=60),
        ),
    ]
