# Generated by Django 3.1.2 on 2021-04-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_auto_20210429_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level4data',
            name='img_src',
            field=models.ImageField(default='', upload_to='static/l4images'),
        ),
    ]
